### ISSUE TITLE
Classpath Exception to Java Files or more permissive license like ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [beehive-lab/Maxine-VM#14]
Can you add Classpath Exception to the Java Files and / or license with alternative license like ASL 2.0

**Comment by kotselidis** [comment]
Unfortunately, we can not currently change the license since MaxineVM is originated from Sun/Oracle Labs and, hence, that decision must be taken in collaboration with Oracle.

**Comment by sirinath** [comment]
Since JDK has classpath exception, is it possible incorporate this by asking Oracle.

**Comment by kotselidis** [comment]
It is a bit more complicated than that since Maxine integrates Graal which is not under ClassPath exception. Therefore any packages that import packages with the Graal integration classes, can not be under the exception. This essentially expands to the whole Maxine project.

However, we are in the process of solving this issue by implementing JVMCI.
We are in touch with Oracle regarding the licensing of Maxine and we hope we will have updates soon.

**Comment by sirinath** [comment]
Anything new on adding classpath exception?

**Comment by kotselidis** [comment]
Unfortunately we have not received any update.
I will follow up on this and post here any news.

**Comment by sirinath** [comment]
Any updates?

Can this be licensed under ASL2.0/MIT?

**Comment by kotselidis** [comment]
Unfortunately no news on that yet.
